#!/usr/bin/env python
# Generated by jaraco.develop (https://bitbucket.org/jaraco/jaraco.develop)
from setuptools import find_packages
setup_params = dict(
	name='adamsrow.tracker',
	use_hg_version=True,
	packages=find_packages(),
	namespace_packages=['adamsrow'],
	zip_safe=False,
	install_requires=[
		# currently, 1.4.19 is required because of the customizations to
		#  nosy.
		'roundup==1.4.19',
		'pytz',
	],
	setup_requires=[
		'hgtools',
	],
	entry_points = dict(
		console_scripts = [
			'adams-row-tracker-create-site = adamsrow.tracker.isapi:create_site',
		]
	),
)
if __name__ == '__main__':
	from setuptools import setup
	setup(**setup_params)
